// Single source of truth for every font-family dropdown across the dashboard
// (song/slide editor toolbar, Bible content/reference tabs). Keep in sync
// with the Google Fonts <link> in index.html for any font that isn't a
// pre-installed system font — otherwise the browser silently falls back.
export const FONT_OPTIONS: string[] = [
  "Lufgord",
  "Arial",
  "Helvetica",
  "Times New Roman",
  "Georgia",
  "Verdana",
  "Tahoma",
  "Trebuchet MS",
  "Impact",
  "Palatino",
  "Garamond",
  "Bookman",
  "Comic Sans MS",
  "Courier New",
  "Lucida Console",
  "Monaco",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Source Sans Pro",
  "Poppins",
  "Nunito",
  "Inter",
  "Playfair Display",
  "Merriweather",
  "PT Serif",
  "Crimson Text",
  "Dancing Script",
  "Great Vibes",
  "Urbanist",
  "Raleway",
  "Work Sans",
  "Rubik",
  "Quicksand",
  "DM Sans",
  "Manrope",
];
