/** Quiet Momentum analytics: readable funnel, trend, territory, and campaign insight without leaderboard noise. */
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { earningsTrend, funnel } from "../data/mockData";
import { ArrowDownRight, ArrowUpRight, Download, Eye, MousePointerClick, UsersRound } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "../lib/toast";

const countries=[{name:"Ghana",value:34},{name:"Nigeria",value:29},{name:"South Africa",value:23},{name:"Kenya",value:14}];
const campaigns=[{name:"Default referral link",clicks:124,trials:16,paid:8},{name:"Summer demo series",clicks:61,trials:9,paid:5},{name:"Church tech workshop",clicks:42,trials:4,paid:3},{name:"Direct introductions",clicks:19,trials:2,paid:2}];
const colors=["#8054F6","#ff2e91","#47b998","#f2aa4c"];

export default function Analytics(){return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[.15em] text-[#8054F6] uppercase">Analytics</p><h1 className="mt-2 text-[34px] font-extrabold">See which introductions become impact.</h1><p className="mt-2 text-sm text-[#77727f]">Follow visits, trials, paid churches, country mix, and campaign quality over time.</p></div><div className="flex gap-2"><Select defaultValue="90"><SelectTrigger className="h-11 w-36 rounded-xl bg-white"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="30">Last 30 days</SelectItem><SelectItem value="90">Last 90 days</SelectItem><SelectItem value="365">This year</SelectItem></SelectContent></Select><Button variant="outline" className="h-11 rounded-xl bg-white" onClick={()=>toast.success("Analytics CSV prepared")}><Download size={17}/></Button></div></div>
<section className="mt-7 grid gap-4 sm:grid-cols-3"><article className="surface rounded-[22px] p-5"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-[#8054F6]"><Eye size={19}/></span><span className="flex items-center gap-1 text-xs font-bold text-emerald-600"><ArrowUpRight size={14}/>12.4%</span></div><div className="metric-number mt-5 text-3xl font-extrabold">246</div><div className="mt-1 text-sm font-bold">Link visits</div><p className="mt-2 text-xs text-[#8b8591]">Unique attributed sessions</p></article><article className="surface rounded-[22px] p-5"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-pink-50 text-[#ff2e91]"><MousePointerClick size={19}/></span><span className="flex items-center gap-1 text-xs font-bold text-emerald-600"><ArrowUpRight size={14}/>4.8%</span></div><div className="metric-number mt-5 text-3xl font-extrabold">23.6%</div><div className="mt-1 text-sm font-bold">Visit to interest</div><p className="mt-2 text-xs text-[#8b8591]">58 interested churches</p></article><article className="surface rounded-[22px] p-5"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><UsersRound size={19}/></span><span className="flex items-center gap-1 text-xs font-bold text-rose-600"><ArrowDownRight size={14}/>1.2%</span></div><div className="metric-number mt-5 text-3xl font-extrabold">58.1%</div><div className="mt-1 text-sm font-bold">Trial to paid</div><p className="mt-2 text-xs text-[#8b8591]">18 active paid churches</p></article></section>
<section className="mt-5 grid gap-5 xl:grid-cols-[1.12fr_.88fr]"><article className="surface rounded-[24px] p-6"><p className="text-xs font-bold tracking-[.12em] text-[#8d8997] uppercase">Conversion funnel</p><h2 className="mt-2 text-xl font-extrabold">How churches progressed</h2><div className="mt-7 space-y-3">{funnel.map((step,i)=><div key={step.label} className="flex items-center gap-4"><div className="w-28 text-xs font-semibold text-[#67616e]">{step.label}</div><div className="flex-1"><div className="relative h-11 overflow-hidden rounded-xl bg-[#f1eef8]"><div className="flex h-full items-center rounded-xl px-4 text-sm font-extrabold text-white" style={{width:`${100-i*18}%`,background:i===3?"#ff2e91":"#8054F6",opacity:1-i*.11}}>{step.value}</div></div></div><div className="w-12 text-right text-xs font-bold text-[#837d89]">{step.rate}</div></div>)}</div></article><article className="surface rounded-[24px] p-6"><p className="text-xs font-bold tracking-[.12em] text-[#8d8997] uppercase">Geography</p><h2 className="mt-2 text-xl font-extrabold">Interested churches by country</h2><div className="mt-3 grid grid-cols-[1fr_.9fr] items-center"><div className="h-[220px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={countries} dataKey="value" nameKey="name" innerRadius={55} outerRadius={85} paddingAngle={4} stroke="none">{countries.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip contentStyle={{border:0,borderRadius:12,boxShadow:"0 12px 30px rgba(39,31,63,.12)",fontSize:12}}/></PieChart></ResponsiveContainer></div><div className="space-y-3">{countries.map((c,i)=><div key={c.name} className="flex items-center justify-between gap-3 text-xs"><span className="flex items-center gap-2 text-[#69636f]"><i className="h-2.5 w-2.5 rounded-full" style={{background:colors[i]}}/>{c.name}</span><b>{c.value}%</b></div>)}</div></div></article></section>
<section className="surface mt-5 rounded-[24px] p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-[.12em] text-[#8d8997] uppercase">Campaign quality</p><h2 className="mt-2 text-xl font-extrabold">Which share paths perform</h2></div></div><div className="mt-5 h-[270px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={campaigns} margin={{left:-16,right:10}}><CartesianGrid stroke="#eeeaf6" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill:"#77717e",fontSize:10}} interval={0}/><YAxis axisLine={false} tickLine={false} tick={{fill:"#aaa6b1",fontSize:10}}/><Tooltip contentStyle={{border:0,borderRadius:12,boxShadow:"0 12px 30px rgba(39,31,63,.12)",fontSize:12}}/><Bar dataKey="clicks" fill="#d9cff8" radius={[6,6,0,0]}/><Bar dataKey="trials" fill="#8054F6" radius={[6,6,0,0]}/><Bar dataKey="paid" fill="#ff2e91" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div><div className="flex flex-wrap gap-5 text-xs text-[#77727f]"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-sm bg-[#d9cff8]"/>Clicks</span><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-sm bg-[#8054F6]"/>Trials</span><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-sm bg-[#ff2e91]"/>Paid</span></div></section></div>}
