/** Quiet Momentum notifications: grouped programme events with visible read state and direct next actions. */
import { Button } from "@/components/ui/button";
import { BellRing, Building2, Check, CircleDollarSign, FileText, ShieldCheck, WalletCards } from "lucide-react";
import { useState } from "react";
import { toast } from "../lib/toast";

const initial=[{id:1,title:"Grace Community Chapel started a trial",detail:"Their Enterprise trial is now active. You can follow the milestone in Referrals.",time:"2 hours ago",icon:Building2,color:"violet",unread:true},{id:2,title:"New commission is pending",detail:"$3.90 was recorded for New Life Worship Centre’s Premium renewal.",time:"Yesterday",icon:CircleDollarSign,color:"pink",unread:true},{id:3,title:"Payment PAY-2026-008 completed",detail:"$82.40 was sent to your verified bank destination and reconciled.",time:"06 Aug",icon:WalletCards,color:"green",unread:false},{id:4,title:"Programme terms updated",detail:"Review the clarified section on trial completion and eligible subscription payments.",time:"01 Aug",icon:FileText,color:"amber",unread:false},{id:5,title:"New sign-in to your account",detail:"Chrome on Windows · Accra, Ghana. If this was not you, secure your account.",time:"29 Jul",icon:ShieldCheck,color:"violet",unread:false}];
export default function Notifications(){const[items,setItems]=useState(initial);function markAll(){setItems(items.map(i=>({...i,unread:false})));toast.success("All notifications marked as read")}return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[.15em] text-[#8054F6] uppercase">Notifications</p><h1 className="mt-2 text-[34px] font-extrabold">Updates that need your attention.</h1><p className="mt-2 text-sm text-[#77727f]">Referral milestones, money movement, programme changes, and account security events.</p></div><Button variant="outline" className="h-11 rounded-xl bg-white" onClick={markAll}><Check className="mr-2" size={17}/>Mark all read</Button></div>
<section className="surface mt-7 overflow-hidden rounded-[24px]"><div className="flex items-center justify-between border-b border-[#efecf5] px-6 py-5"><div><h2 className="text-xl font-extrabold">All updates</h2><p className="mt-1 text-xs text-[#8a8491]">{items.filter(i=>i.unread).length} unread notifications</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eee9ff] text-[#8054F6]"><BellRing size={19}/></span></div><div>{items.map(item=><button key={item.id} onClick={()=>setItems(items.map(i=>i.id===item.id?{...i,unread:false}:i))} className={`flex w-full gap-4 border-b border-[#f0edf5] px-6 py-5 text-left transition last:border-0 hover:bg-[#fbfaff] ${item.unread?"bg-[#faf8ff]":"bg-white"}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${item.color==="pink"?"bg-pink-50 text-[#ff2e91]":item.color==="green"?"bg-emerald-50 text-emerald-600":item.color==="amber"?"bg-amber-50 text-amber-600":"bg-violet-50 text-[#8054F6]"}`}><item.icon size={18}/></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="text-sm font-bold">{item.title}</span>{item.unread&&<i className="h-2 w-2 rounded-full bg-[#ff2e91]"/>}</div><p className="mt-1 text-xs leading-5 text-[#7e7885]">{item.detail}</p></div><span className="shrink-0 text-[10px] font-semibold text-[#aaa4b0]">{item.time}</span></button>)}</div></section></div>}
