/** Quiet Momentum payment history: reconciled payout records, references, and exportable statements. */
import StatusPill from "../components/StatusPill";
import { Button } from "@/components/ui/button";
import { payouts } from "../data/mockData";
import { Download, FileText, ReceiptText, Search, WalletCards } from "lucide-react";
import { toast } from "../lib/toast";

export default function PaymentHistory(){return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[.15em] text-[#8054F6] uppercase">Payment history</p><h1 className="mt-2 text-[34px] font-extrabold">Paid, referenced, and easy to reconcile.</h1><p className="mt-2 text-sm text-[#77727f]">Review completed and failed payouts, payment references, and downloadable statements.</p></div><Button variant="outline" className="h-11 rounded-xl bg-white" onClick={()=>toast.success("Annual statement prepared") }><Download className="mr-2" size={17}/>2026 statement</Button></div>
<section className="mt-7 grid gap-5 sm:grid-cols-3"><article className="surface rounded-[22px] p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-[#8054F6]"><WalletCards size={19}/></span><div className="metric-number mt-5 text-3xl font-extrabold">$253.00</div><div className="mt-1 text-sm font-bold">Paid in 2026</div><p className="mt-2 text-xs text-[#8b8591]">Four completed withdrawals</p></article><article className="surface rounded-[22px] p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><ReceiptText size={19}/></span><div className="metric-number mt-5 text-3xl font-extrabold">4</div><div className="mt-1 text-sm font-bold">Reconciled payments</div><p className="mt-2 text-xs text-[#8b8591]">No unresolved payout failures</p></article><article className="surface rounded-[22px] p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-pink-50 text-[#ff2e91]"><FileText size={19}/></span><div className="metric-number mt-5 text-3xl font-extrabold">$0.00</div><div className="mt-1 text-sm font-bold">Fees recorded</div><p className="mt-2 text-xs text-[#8b8591]">Prototype destination has no fixed fee</p></article></section>
<section className="surface mt-5 overflow-hidden rounded-[24px]"><div className="flex items-center justify-between px-6 py-5"><div><p className="text-xs font-bold tracking-[.12em] text-[#8d8997] uppercase">Payouts</p><h2 className="mt-2 text-xl font-extrabold">Transaction history</h2></div><Button variant="outline" size="icon" className="rounded-xl bg-white"><Search size={17}/></Button></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead className="bg-[#faf9fd] text-[10px] font-bold tracking-[.1em] text-[#918c99] uppercase"><tr><th className="px-6 py-3">Reference</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Requested</th><th className="px-4 py-3">Completed</th><th className="px-4 py-3">Method</th><th className="px-4 py-3">Status</th><th className="px-6 py-3 text-right">Statement</th></tr></thead><tbody>{payouts.map(row=><tr key={row.id} className="border-t border-[#f0edf5] text-[13px] hover:bg-[#fbfaff]"><td className="px-6 py-4 font-mono text-xs text-[#88828f]">{row.id}</td><td className="px-4 py-4 font-extrabold">{row.amount}</td><td className="px-4 py-4 text-[#716c78]">{row.requested}</td><td className="px-4 py-4 text-[#716c78]">{row.completed}</td><td className="px-4 py-4 text-[#716c78]">{row.method}</td><td className="px-4 py-4"><StatusPill label={row.status}/></td><td className="px-6 py-4 text-right"><Button variant="ghost" size="sm" className="font-bold text-[#8054F6]" onClick={()=>toast.success(`${row.id} statement prepared`)}><Download className="mr-2" size={14}/>PDF</Button></td></tr>)}</tbody></table></div></section></div>}
