/** Quiet Momentum church detail: one transparent journey, clear earnings eligibility, and partner-safe activity. */
import StatusPill from "../components/StatusPill";
import { Button } from "@/components/ui/button";
import { churches } from "../data/mockData";
import { ArrowLeft, Building2, CalendarDays, Check, CircleDollarSign, Clock3, Link2, Mail, MapPin, MoreHorizontal, Phone, ShieldCheck } from "lucide-react";
import { Link, useParams } from "wouter";

const stages = ["Interest", "Trial", "Onboarding", "Trial complete", "Paying"];

export default function ReferralDetail() {
  const { id } = useParams<{ id: string }>(); const church = churches.find(c => c.id === id) || churches[0];
  const current = church.status === "Active subscriber" ? 4 : church.status === "Trial complete" ? 3 : church.status === "Getting set up" ? 2 : church.status === "Trial active" ? 1 : 0;
  return <div>
    <Link href="/referrals" className="inline-flex items-center gap-2 text-sm font-bold text-[#77717f] transition hover:text-[#8054F6]"><ArrowLeft size={16} />Back to referrals</Link>
    <div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex items-start gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-[18px] bg-[#8054F6] font-[Manrope] text-base font-extrabold text-white">{church.church.split(" ").slice(0,2).map(w => w[0]).join("")}</span><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-[30px] font-extrabold sm:text-[36px]">{church.church}</h1><StatusPill label={church.status} /></div><p className="mt-2 flex items-center gap-1.5 text-sm text-[#7a7582]"><MapPin size={14} />{church.city}, {church.country} · Introduced {church.date}</p></div></div><Button variant="outline" size="icon" className="rounded-xl bg-white"><MoreHorizontal size={19}/></Button></div>

    <section className="surface mt-7 rounded-[24px] p-6 sm:p-7"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-bold tracking-[.12em] text-[#8054F6] uppercase">Client journey</p><h2 className="mt-2 text-xl font-extrabold">{church.nextStep}</h2></div>{church.trialEnds && <span className="flex items-center gap-2 rounded-xl bg-[#f5f2ff] px-3 py-2 text-xs font-semibold text-[#6642c8]"><CalendarDays size={15}/>Trial ends {church.trialEnds}</span>}</div><div className="mt-7 grid grid-cols-5 gap-1 sm:gap-3">{stages.map((stage, index) => <div key={stage} className="relative"><div className={`momentum-line absolute left-1/2 right-[-55%] top-4 ${index === stages.length - 1 ? "hidden" : ""}`} style={{ background: index < current ? "#8054F6" : undefined }} /><div className={`relative z-10 grid h-8 w-8 place-items-center rounded-full border-4 border-white text-[10px] font-bold shadow-sm ${index <= current ? "bg-[#8054F6] text-white" : "bg-[#eae6f4] text-[#96909f]"}`}>{index < current ? <Check size={14}/> : index + 1}</div><div className={`mt-2 max-w-24 text-[10px] font-semibold sm:text-xs ${index <= current ? "text-[#443d4e]" : "text-[#aaa4b0]"}`}>{stage}</div></div>)}</div><p className="mt-6 rounded-xl bg-[#faf9fd] p-3 text-xs leading-5 text-[#736e7b]">This view contains milestones Q-Worship can safely share. Internal sales notes and sensitive billing details remain private.</p></section>

    <section className="mt-5 grid gap-5 xl:grid-cols-[1fr_.72fr]"><div className="space-y-5"><article className="surface rounded-[24px] p-6"><p className="text-xs font-bold tracking-[.12em] text-[#8d8997] uppercase">Activity timeline</p><h2 className="mt-2 text-xl font-extrabold">What happened</h2><div className="relative mt-6 space-y-6 before:absolute before:bottom-2 before:left-[15px] before:top-2 before:w-px before:bg-[#e5e0ef]">{[
      ["Trial milestone updated", church.nextStep, "Today", Clock3], ["Q-Worship follow-up completed", "The church received an onboarding and product guidance call.", "19 Aug 2026", Phone], ["Referral attributed to you", `${church.source} matched your referrer account.`, church.date, Link2]
    ].map(([title, detail, date, Icon]: any, i) => <div key={title} className="relative flex gap-4"><span className={`z-10 grid h-8 w-8 shrink-0 place-items-center rounded-full ${i === 0 ? "bg-[#8054F6] text-white" : "bg-[#f1edf9] text-[#8054F6]"}`}><Icon size={14}/></span><div className="pt-0.5"><div className="text-sm font-bold">{title}</div><p className="mt-1 text-xs leading-5 text-[#7f7a86]">{detail}</p><div className="mt-1.5 text-[10px] font-semibold text-[#aaa5b1]">{date}</div></div></div>)}</div></article><article className="surface rounded-[24px] p-6"><p className="text-xs font-bold tracking-[.12em] text-[#8d8997] uppercase">Q-Worship handoff</p><h2 className="mt-2 text-xl font-extrabold">What the team manages</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{["Product demonstration and trial support", "Subscription, billing, and customer success", "Eligibility and duplicate verification", "Secure handling of church account data"].map(item => <div className="flex gap-2 rounded-xl bg-[#faf9fd] p-3 text-xs font-semibold text-[#5e5965]" key={item}><ShieldCheck className="shrink-0 text-emerald-600" size={16}/>{item}</div>)}</div></article></div>
    <aside className="space-y-5"><article className="surface rounded-[24px] p-6"><p className="text-xs font-bold tracking-[.12em] text-[#8d8997] uppercase">Referral summary</p><div className="mt-5 space-y-4">{[[Building2,"Plan",church.plan],[Link2,"Source",church.source],[CircleDollarSign,"Current monthly commission", church.monthlyCommission ? `$${church.monthlyCommission.toFixed(2)}` : "Not active"]].map(([Icon,label,value]: any) => <div className="flex items-start gap-3" key={label}><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f2eeff] text-[#8054F6]"><Icon size={17}/></span><div><div className="text-[10px] font-bold tracking-[.08em] text-[#96909d] uppercase">{label}</div><div className="mt-1 text-sm font-bold">{value}</div></div></div>)}</div></article><article className="surface rounded-[24px] p-6"><p className="text-xs font-bold tracking-[.12em] text-[#8d8997] uppercase">Church contact</p><div className="mt-4 text-sm font-bold">{church.contact}</div><div className="mt-3 flex items-center gap-2 text-xs text-[#7f7986]"><Mail size={14}/>Contact details managed by Q-Worship</div><p className="mt-4 border-t border-[#efecf4] pt-4 text-xs leading-5 text-[#8a8591]">Contact information is masked in the referrer view unless the church has consented to direct follow-up.</p></article></aside></section>
  </div>;
}
