/** Quiet Momentum resources: approved enablement materials organised for fast field use. */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { BookOpen, Download, FileText, Film, Heart, MonitorPlay, Search, Star } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "../lib/toast";
import MomentumArtwork from "../components/MomentumArtwork";

const resources=[{title:"Q-Worship product overview",type:"Sales guide",meta:"PDF · 4.2 MB",icon:FileText,color:"violet",desc:"A concise introduction to the complete church presentation platform."},{title:"Hands-Free Bible demo script",type:"Demo toolkit",meta:"DOCX · 820 KB",icon:MonitorPlay,color:"pink",desc:"A guided 12-minute demonstration for pastors and media teams."},{title:"Plans and pricing explainer",type:"Sales guide",meta:"PDF · 1.1 MB",icon:FileText,color:"green",desc:"Current public plan comparison with approved positioning language."},{title:"Church tech workshop deck",type:"Event toolkit",meta:"PPTX · 8.5 MB",icon:BookOpen,color:"amber",desc:"Presentation materials for conferences, workshops, and denominational events."},{title:"OBS and NDI walkthrough",type:"Video",meta:"MP4 · 09:42",icon:Film,color:"violet",desc:"A practical product video for church broadcast and technical teams."},{title:"West Africa representative playbook",type:"Regional guide",meta:"PDF · 2.6 MB",icon:Star,color:"pink",desc:"Territory-sensitive outreach, qualification, and follow-up guidance."}];
export default function Resources(){const[search,setSearch]=useState("");const[tab,setTab]=useState("all");const visible=useMemo(()=>resources.filter(r=>r.title.toLowerCase().includes(search.toLowerCase())&&(tab==="all"||r.type.toLowerCase().includes(tab))),[search,tab]);return <div><div><p className="text-xs font-bold tracking-[.15em] text-[#8054F6] uppercase">Resources</p><h1 className="mt-2 text-[34px] font-extrabold">Approved tools for every conversation.</h1><p className="mt-2 text-sm text-[#77727f]">Prepare demos, explain the product clearly, and use the latest Q-Worship materials in your territory.</p></div>
<section className="surface-soft relative mt-7 overflow-hidden rounded-[26px] p-7"><MomentumArtwork variant="resource"/><div className="relative max-w-[58%] min-w-[280px]"><span className="inline-flex items-center gap-2 rounded-full bg-[#eee9ff] px-3 py-1 text-[11px] font-bold text-[#7048d8]"><Star size={13}/>Featured guide</span><h2 className="mt-4 text-2xl font-extrabold">Run a confident Q-Worship demo.</h2><p className="mt-2 max-w-lg text-sm leading-6 text-[#6f6976]">Use the approved flow to demonstrate voice-powered Bible search, service planning, live presentation, and OBS integration.</p><Button className="violet-button mt-5 rounded-xl" onClick={()=>toast.success("Demo toolkit download prepared")}><Download className="mr-2" size={16}/>Download demo toolkit</Button></div></section>
<div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><Tabs value={tab} onValueChange={setTab}><TabsList className="h-auto flex-wrap rounded-xl bg-white p-1"><TabsTrigger value="all">All</TabsTrigger><TabsTrigger value="sales">Sales guides</TabsTrigger><TabsTrigger value="demo">Demo tools</TabsTrigger><TabsTrigger value="video">Videos</TabsTrigger><TabsTrigger value="regional">Regional</TabsTrigger></TabsList></Tabs><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#aaa6b2]" size={16}/><Input value={search} onChange={e=>setSearch(e.target.value)} className="h-10 w-full rounded-xl bg-white pl-9 sm:w-64" placeholder="Search resources"/></div></div>
<section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(r=><article key={r.title} className="surface group rounded-[22px] p-5 transition duration-200 hover:-translate-y-0.5"><div className="flex items-start justify-between"><span className={`grid h-11 w-11 place-items-center rounded-xl ${r.color==="pink"?"bg-pink-50 text-[#ff2e91]":r.color==="green"?"bg-emerald-50 text-emerald-600":r.color==="amber"?"bg-amber-50 text-amber-600":"bg-violet-50 text-[#8054F6]"}`}><r.icon size={20}/></span><button aria-label={`Favourite ${r.title}`} className="grid h-9 w-9 place-items-center rounded-lg text-[#aaa4b0] hover:bg-pink-50 hover:text-[#ff2e91]"><Heart size={17}/></button></div><div className="mt-5 text-[10px] font-bold tracking-[.1em] text-[#8054F6] uppercase">{r.type}</div><h2 className="mt-2 text-lg font-extrabold">{r.title}</h2><p className="mt-2 min-h-10 text-xs leading-5 text-[#807a87]">{r.desc}</p><div className="mt-5 flex items-center justify-between border-t border-[#efecf5] pt-4"><span className="text-[11px] text-[#9b95a1]">{r.meta}</span><Button variant="ghost" size="sm" className="font-bold text-[#8054F6]" onClick={()=>toast.success(`${r.title} prepared for download`)}><Download className="mr-2" size={14}/>Download</Button></div></article>)}</section></div>}
