/** Quiet Momentum support: direct self-service help, contextual contact, and transparent ticket status. */
import StatusPill from "../components/StatusPill";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { BookOpen, CircleDollarSign, Headphones, LifeBuoy, MessageSquarePlus, Paperclip, Search, ShieldCheck, WalletCards } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "../lib/toast";

export default function Support(){const[open,setOpen]=useState(false);function submit(e:FormEvent){e.preventDefault();setOpen(false);toast.success("Support request created",{description:"Ticket QWS-1842 · We will notify you when the team replies."})}return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[.15em] text-[#8054F6] uppercase">Support</p><h1 className="mt-2 text-[34px] font-extrabold">Help without the guesswork.</h1><p className="mt-2 text-sm text-[#77727f]">Search quick answers or create a support request with the context the team needs.</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="violet-button h-11 rounded-xl px-5 font-bold"><MessageSquarePlus className="mr-2" size={17}/>New support request</Button></DialogTrigger><DialogContent className="referee-portal-dialog rounded-[24px] sm:max-w-[560px]"><DialogHeader><DialogTitle className="text-2xl">Create a support request</DialogTitle><DialogDescription>Do not include bank passwords or full payment-card details.</DialogDescription></DialogHeader><form onSubmit={submit} className="mt-3 space-y-4"><label><Label>Topic</Label><Select required><SelectTrigger className="mt-2 h-11"><SelectValue placeholder="Choose a topic"/></SelectTrigger><SelectContent><SelectItem value="referral">Referral status or attribution</SelectItem><SelectItem value="earnings">Earnings or commission</SelectItem><SelectItem value="payout">Withdrawal or payment</SelectItem><SelectItem value="account">Account and security</SelectItem><SelectItem value="resources">Resources and demos</SelectItem></SelectContent></Select></label><label><Label>Subject</Label><Input required className="mt-2 h-11 bg-[#f8f7fb]" placeholder="A short summary"/></label><label><Label>Message</Label><Textarea required className="mt-2 min-h-28 bg-[#f8f7fb]" placeholder="Tell us what happened, when it happened, and any reference involved."/></label><Button type="button" variant="outline" className="w-full border-dashed"><Paperclip className="mr-2" size={16}/>Attach a screenshot or document</Button><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" className="violet-button">Create request</Button></DialogFooter></form></DialogContent></Dialog></div>
<section className="surface mt-7 rounded-[24px] p-6 sm:p-7"><div className="mx-auto max-w-2xl text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#eee9ff] text-[#8054F6]"><LifeBuoy size={23}/></span><h2 className="mt-4 text-2xl font-extrabold">What can we help you solve?</h2><div className="relative mt-5"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#aaa6b2]" size={18}/><Input className="h-13 rounded-xl bg-[#f7f6fa] pl-11 text-sm" placeholder="Search referral, commission, withdrawal, or account help"/></div></div><div className="mt-7 grid gap-3 md:grid-cols-4">{[[CircleDollarSign,"Commission explained","Estimated, pending, and available"],[WalletCards,"Payout help","Methods, thresholds, and timing"],[ShieldCheck,"Account security","Password, MFA, and verification"],[BookOpen,"Demo resources","Guides and approved materials"]].map(([Icon,t,d]:any)=><button key={t} onClick={()=>toast.info(`${t} articles opened`)} className="rounded-[18px] bg-[#faf9fd] p-4 text-left transition hover:bg-[#f1edff]"><Icon className="text-[#8054F6]" size={19}/><div className="mt-3 text-sm font-bold">{t}</div><div className="mt-1 text-[11px] leading-4 text-[#8a8491]">{d}</div></button>)}</div></section>
<section className="mt-5 grid gap-5 xl:grid-cols-[1.12fr_.88fr]"><article className="surface rounded-[24px] p-6"><p className="text-xs font-bold tracking-[.12em] text-[#8d8997] uppercase">Frequently asked</p><h2 className="mt-2 text-xl font-extrabold">Programme answers</h2><Accordion type="single" collapsible className="mt-4"><AccordionItem value="one"><AccordionTrigger>When does a referral start earning commission?</AccordionTrigger><AccordionContent>A referral becomes commission-eligible after the configured trial or qualification period and when the first eligible paid invoice settles. Estimated potential is not withdrawable.</AccordionContent></AccordionItem><AccordionItem value="two"><AccordionTrigger>Why is a commission pending?</AccordionTrigger><AccordionContent>Pending commission is linked to a qualifying payment but has not completed the settlement and refund-hold period configured for the programme.</AccordionContent></AccordionItem><AccordionItem value="three"><AccordionTrigger>Can I register a church I met offline?</AccordionTrigger><AccordionContent>Yes. Use “Introduce a church” in the Referral Hub. Q-Worship checks consent, duplicates, and programme eligibility before attribution is confirmed.</AccordionContent></AccordionItem><AccordionItem value="four"><AccordionTrigger>What happens when a church cancels?</AccordionTrigger><AccordionContent>Future recurring commission stops when the subscription ends. Cleared historical commission remains subject to the programme terms, refunds, chargebacks, and confirmed adjustments.</AccordionContent></AccordionItem></Accordion></article><article className="surface rounded-[24px] p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold tracking-[.12em] text-[#8d8997] uppercase">Your requests</p><h2 className="mt-2 text-xl font-extrabold">Recent support</h2></div><Headphones className="text-[#8054F6]" size={21}/></div><div className="mt-5 rounded-[18px] border border-[#ebe7f2] p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-bold">Attribution review for Faith Tabernacle</div><div className="mt-1 text-[11px] text-[#918b98]">Ticket QWS-1798 · Updated 22 Aug</div></div><StatusPill label="Processing"/></div><p className="mt-3 text-xs leading-5 text-[#7f7986]">Programme team is reviewing the explicit referral code against the existing account record.</p></div><Button variant="outline" className="mt-4 w-full rounded-xl bg-white" onClick={()=>toast.info("Ticket conversation opened")}>Open conversation</Button></article></section></div>}
