FROM node:20-alpine AS builder

WORKDIR /app

COPY apps/marketing/package.json ./
COPY apps/marketing/ ./

RUN npm install
RUN npm run build

FROM nginx:alpine

RUN echo $'server {\n\
    listen 80;\n\
    location / {\n\
        root   /usr/share/nginx/html;\n\
        index  index.html index.htm;\n\
        try_files $uri $uri/ /index.html;\n\
    }\n\
}' > /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
