// @ts-nocheck
/**
 * seed-bible-translations.ts
 *
 * Upserts AMP and MSG Bible text into the existing BibleVerse collection
 * by reading the pre-converted flat JSON files.
 *
 * Each record: { book, chapter, verse, text }
 * Maps to BibleVerse fields: { bookName, chapter, verse, amp/msg }
 *
 * Run:
 *   npx tsx apps/server/src/scripts/seed-bible-translations.ts
 *   OR
 *   ts-node apps/server/src/scripts/seed-bible-translations.ts
 */

import mongoose from 'mongoose';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { BibleVerse } from '../modules/bible/bible.model.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ── Config ────────────────────────────────────────────────────────────────────
// Point to your flat JSON files (generated by convert_legacy_bibles.py)
const TRANSLATION_FILES: { version: 'amp' | 'msg'; filePath: string }[] = [
  {
    version: 'amp',
    filePath: path.join(
      __dirname,
      '../../../../../../Qwroship-desktop/apps/client/public/data/bibles/amp.json'
    ),
  },
  {
    version: 'msg',
    filePath: path.join(
      __dirname,
      '../../../../../../Qwroship-desktop/apps/client/public/data/bibles/msg.json'
    ),
  },
];

// Testament helper: books 1-39 OT, 40-66 NT
const OT_BOOKS = new Set([
  'Genesis','Exodus','Leviticus','Numbers','Deuteronomy','Joshua','Judges','Ruth',
  '1 Samuel','2 Samuel','1 Kings','2 Kings','1 Chronicles','2 Chronicles','Ezra',
  'Nehemiah','Esther','Job','Psalms','Proverbs','Ecclesiastes','Song of Solomon',
  'Isaiah','Jeremiah','Lamentations','Ezekiel','Daniel','Hosea','Joel','Amos',
  'Obadiah','Jonah','Micah','Nahum','Habakkuk','Zephaniah','Haggai','Zechariah','Malachi',
]);

async function seedTranslation(version: 'amp' | 'msg', filePath: string) {
  if (!fs.existsSync(filePath)) {
    console.error(`  ❌ File not found: ${filePath}`);
    return;
  }

  console.log(`\n📖 Loading ${version.toUpperCase()} from: ${filePath}`);
  const raw = fs.readFileSync(filePath, 'utf-8');
  const verses: { book: string; chapter: number; verse: number; text: string }[] = JSON.parse(raw);

  // Filter out empty verses — no point storing blanks
  const nonEmpty = verses.filter(v => v.text && v.text.trim().length > 0);
  console.log(`  Total verses in file: ${verses.length} | Non-empty: ${nonEmpty.length}`);

  const BATCH_SIZE = 1000;
  let written = 0;

  for (let i = 0; i < nonEmpty.length; i += BATCH_SIZE) {
    const batch = nonEmpty.slice(i, i + BATCH_SIZE);

    const operations = batch.map(v => ({
      updateOne: {
        filter: {
          bookName: v.book,
          chapter: v.chapter,
          verse: v.verse,
        },
        update: {
          $set: {
            bookName: v.book,
            testament: OT_BOOKS.has(v.book) ? 'old' : 'new',
            chapter: v.chapter,
            verse: v.verse,
            [version]: v.text,
          },
        },
        upsert: true,
      },
    }));

    await BibleVerse.bulkWrite(operations, { ordered: false });
    written += batch.length;
    console.log(`  ${version.toUpperCase()} → ${written}/${nonEmpty.length} verses written`);
  }

  console.log(`  ✅ ${version.toUpperCase()} seeding complete!`);
}

async function main() {
  const MONGO_URI =
    process.env.MONGO_URI ||
    'mongodb+srv://kayyadams360_db_user:V4e9BhRfLKHL12h4@qworship.bki11v4.mongodb.net/';

  console.log(`\n🔌 Connecting to MongoDB...`);
  await mongoose.connect(MONGO_URI);
  console.log(`✅ Connected.\n`);

  for (const { version, filePath } of TRANSLATION_FILES) {
    await seedTranslation(version, filePath);
  }

  // Quick validation: sample a Genesis 1:1 from each
  console.log('\n🔍 Validation check — Genesis 1:1:');
  const verse = await BibleVerse.findOne({ bookName: 'Genesis', chapter: 1, verse: 1 }).lean();
  if (verse) {
    console.log(`  KJV: ${(verse as any).kjv?.substring(0, 60) || '(empty)'}...`);
    console.log(`  AMP: ${(verse as any).amp?.substring(0, 60) || '(empty)'}...`);
    console.log(`  MSG: ${(verse as any).msg?.substring(0, 60) || '(empty)'}...`);
  } else {
    console.log('  ⚠️  Genesis 1:1 not found in DB!');
  }

  await mongoose.disconnect();
  console.log('\n✅ Done. Connection closed.');
  process.exit(0);
}

main().catch(err => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
